name: app_review
description: Request and Write Reviews and Open Store Listing for Android and iOS in Flutter.
version: 2.2.0
environment:
  sdk: ^3.5.0
  flutter: ^3.38.5
resolution: workspace
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/packages.dart
repository: https://github.com/rodydavis/packages.dart


dependencies:
  http: ^1.2.0

  url_launcher: ^6.3.0
  package_info_plus: ^9.0.0
  
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.appleeducate.appreview
        pluginClass: AppReviewPlugin
      ios:
        pluginClass: AppReviewPlugin
