name: pocketbase_sync
description: A Flutter package for offline-first syncing with PocketBase.
version: 0.0.1
homepage: https://github.com/fluttercommunity/flutter_whatsnew
maintainer: Rody Davis (@rodydavis)
resolution: workspace
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter
  pocketbase: ^0.23.0+1 
  drift: ^2.14.0
  collection: ^1.18.0
  uuid: ^4.0.0
  path: ^1.9.0
  json_annotation: ^4.8.0
  logging: ^1.3.0
  hlc_dart: ^1.0.0
  diff_algorithims:
    path: ../diff_algorithims

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.0
  drift_dev: ^2.14.0
  mockito: ^5.4.0
  http: ^1.6.0
  diff_match_patch: ^0.4.1
  archive: ^4.0.7
  glados: ^1.1.7
