version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/breakpoint"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_sms"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_vibrate"
    schedule:
      interval: "daily"

  - package-ecosystem: "pub"
    directory: "/packages/flutter_whatsnew"
    schedule:
      interval: "daily"
