name: packages_dart_rodydavis
publish_to: none

environment:
  sdk: ^3.5.0

workspace:
  - packages/flutter_vibrate
  - packages/flutter_sms
  - packages/flutter_whatsnew
  - packages/breakpoint
  - packages/app_review
  - packages/undo