name: undo
description: A Undo/Redo Library for Flutter
version: 1.6.0
homepage: https://github.com/rodydavis/packages.dart
repository: https://github.com/rodydavis/packages.dart
maintainer: Rody Davis (@rodydavis)
resolution: workspace

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9
