name: flutter_whatsnew
description: A new Flutter package to show updates to users.
version: 1.1.0+1
homepage: https://github.com/rodydavis/packages.dart
repository: https://github.com/rodydavis/packages.dart
maintainer: Rody Davis (@rodydavis)
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
