name: flutter_vibrate
description: A Haptic Feedback and Vibration plugin.
version: 1.4.0
environment:
  sdk: ^3.5.0
  flutter: ^3.38.5
resolution: workspace
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/packages.dart
repository: https://github.com/rodydavis/packages.dart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  pigeon: ^26.1.5

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.vibrate
        pluginClass: VibratePlugin
      ios:
        pluginClass: VibratePlugin
