name: flutter_vibrate
description: A Haptic Feedback plugin.
version: 1.3.0
environment:
  sdk: ^3.10.4
  flutter: ^3.38.5
maintainer: Rody Davis (@rodydavis)
homepage: https://github.com/rodydavis/plugins
repository: https://github.com/rodydavis/flutter_vibrate
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  pigeon: ^26.1.5

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.vibrate
        pluginClass: VibratePlugin
      ios:
        pluginClass: VibratePlugin
