name: diff_algorithims
description: A set of diffing algorithims for Dart
version: 0.0.1
homepage: https://github.com/example/pocketbase_sync
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.38.5
dev_dependencies:
  test: ^1.26.3
