name: pocketbase_auth
description: Pocketbase auth client with built in UI screens and token refresh
publish_to: 'none'
version: 1.0.0+1
homepage: https://github.com/fluttercommunity/flutter_whatsnew
maintainer: Rody Davis (@rodydavis)
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  fetch_client: ^1.2.0
  pocketbase: ^0.23.0+1
  url_launcher: ^6.3.2
  stream_transform: ^2.1.1
  http_interceptor: ^2.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
