name: flutter_sms
description: A Flutter plugin to send SMS and MMS on iOS and Android.
version: 3.0.0
homepage: https://github.com/rodydavis/packages.dart
repository: https://github.com/rodydavis/packages.dart
maintainer: Rody Davis (@rodydavis)
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ^3.38.5

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_launcher: ^6.1.10
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^26.1.5

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_sms
        pluginClass: FlutterSmsPlugin
      ios:
        pluginClass: SwiftFlutterSmsPlugin

