name: web_file_system
description: A high-performance, asynchronous file system for the web using IDB and OPFS.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/fluttercommunity/flutter_whatsnew
maintainer: Rody Davis (@rodydavis)

environment:
  sdk: ^3.5.0
  flutter: ^3.38.5

dependencies:
  file: ^7.0.0
  path: ^1.9.0
  web: ^1.1.1
  uuid: ^4.0.0
  mime: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
